spring:
    mvc:
      view:
        prefix: "/"
        suffix: ".html"
    profiles:
      active: dev
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
id:
  gen:
    worker: 1
    datacenter: 1